### ISSUE TITLE
MEFISTO on spatial datasets with replicates

### ISSUE THREAD

**Issue by jwrth** [bioFAM/MEFISTO_tutorials#3]
Hi all,

Thanks a lot for publishing this great tool and for all the nice tutorials! I am currently testing it on spatial datasets that I acquired. I have two conditions in the experiment and multiple replicates per condition and was wondering if it is possible to include multiple replicates of spatial datasets into the analysis. And if it is possible, how should I do it? Should I treat them as different "views" or add a third covariate to differentiate between the replicates? I'm not a statistician by training and would be very grateful for a few inputs on that topic!

Thanks a lot in advance!!

**Comment by bv2** [comment]
Hi Johannes,
thanks for your interest in MEFISTO! If the spatial coordinated between your different replicates and conditions are aligned (or can be aligned) across experiments you could consider to include them as different groups into the model. (Assuming that in all replicates you measure the same features which would be the "view"). If spatial coordinates are not aligned, it might be better to use the model on each replicate separately and post-hoc compare the inferred factors, e.g. are they the same across replicates, how do they change between conditions... Feel free to also reach out via Slack if you want to discuss model setup and interpretation of the results in more detail: https://join.slack.com/t/mofahelp/shared_invite/enQtMjcxNzM3OTE3NjcxLWNhZmM1MDRlMTZjZWRmYWJjMGFmMDkzNDBmMDhjYmJmMzdlYzU4Y2EzYTI1OGExNzM2MmUwMzJkZmVjNDkxNGI

**Comment by jwrth** [comment]
Hi Britta,
Thanks a lot for your reply! I'll see if I can do it as you suggested and if I have further questions I'll check out the Slack channel.
